### ISSUE TITLE
doc: note default lowercase file name

### ISSUE THREAD

**Issue by bytesun** [buildwithjuno/docs#15]
Noticed the file name is converted to lowercase by default when using API(uploadFile) to upload file, it might be worth to mention it in document.

In my case, I save the original file name(e.g. xexrEDdkiEEOX) for future reference when uploading file, but they are not match when I use it because it's lowercase(e.g. xexreddkieeox) in storage.

**Comment by peterpeterparker** [comment]
Thanks. Documented in #16. I'll deploy the website later this evening (working on a blog post that should go live as well).
