### ISSUE TITLE
Improve CLI documentation for Windows Powershell

### ISSUE THREAD

**Issue by peterpeterparker** [buildwithjuno/docs#25]
Unless we find some way to improve the CLI for Windows Powershell, users of such types of terminal have to add `npm` to their path if not yet present. 

Therefore we can probably add a notice in the CLI about.

Something like:

```
:::note

If you are using Windows Powershell, after having installed the CLI please make sure npm is in your path:

C:\Users\{PC_NAME}\AppData\Roaming\npm

:::
```

**Comment by html-css-js-art** [comment]
Hey! Saurabh Here, Thanks for Adding this Sure it will Help Others 🌟
